### ISSUE TITLE
Missing Autofield setting

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/acdh-django-charts#3]
* django_charts version: 0.5.3
* Django version: 4.1
* Python version: 3.10.5
* Operating System: Debian bullseye

### Description

The app causes warnings when run within other projects, seemingly due to missing a `default_auto_field` setting.

See [Django release notes for 3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys) and [this issue in apis-rdf-devops](https://github.com/acdh-oeaw/apis-rdf-devops/issues/64) for more details.

**Comment by b1rger** [comment]
See #2
